#! python3
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
# Finished

def power(a, n):

	mylist = []
	while n > 2:
		if n % 2 == 0:
			n = n//2
			a = a**2
		else:
			mylist.append(a)
			n = n//2
			a = a**2

	product = a**n
	for x in mylist:
		product *= x

	return product

limit = 100
res = 0
unique_values = []
for a in range(2, limit + 1, 1):
	for n in range(2, limit + 1, 1):
		res = power(a, n)
		if res not in unique_values:
			unique_values.append(res)

print(len(unique_values))